// DeclarationPage.jsx
import React,{useEffect} from "react";
import { useLocation } from "react-router-dom";
import "./aiagreement.css";
import axios from "axios";

export default function DeclarationPage() {
     useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  

  const location = useLocation();
  const finalcontent= location.state?.final || "";
  const quizname=location.state?.quizname || ""

  const payload={
    testname:quizname,questions:finalcontent,
  }

  
  const handlePrepareQuiz = async() => {

   const API_BASE_URL = window.location.hostname === 'localhost'
  ? 'http://localhost:4000'
  : 'https://quiz-backend-x32j.onrender.com';
const aiquestionpost = await axios.post(`${API_BASE_URL}/api/v1/quizopt/declaration`,payload)      
  };

  return (
    <div className="declaration-container">
      <h1 className="title">Creator's Declaration</h1>

      <div className="declaration-content">
        <p>
          I, the creator of this quiz, solemnly declare that I have thoroughly reviewed all the questions generated by the AI. Each question has been verified for accuracy, clarity, and relevance to the intended topic and audience.
        </p>

        <p>
          I acknowledge my responsibility to ensure that:
        </p>

        <ol>
          <li>All questions are free from bias, offensive content, or misleading information.</li>
          <li>The answer options are correctly aligned with the respective questions.</li>
          <li>Each correct answer is thoroughly reviewed and validated.</li>
          <li>Any necessary edits to the AI-generated content have been completed by me.</li>
          <li>The quiz aligns with the educational or assessment goals it is intended to serve.</li>
        </ol>

        <p>
          By clicking the button below, I confirm that I am satisfied with the quality of the quiz content and hereby proceed to finalize the quiz for deployment or further usage.
        </p>
      </div>

      <div className="button-container">
        <button className="prepare-btn" onClick={handlePrepareQuiz}>
          Prepare Quiz
        </button>
      </div>
    </div>
  );
}
